name = "nezutero"
description = "Software Engineer, human."
license = "MIT"
homepage = "https://github.com/nezutero/nezutero.dev"
min_version = "0.19.0"

[author]
name = "nezutero"
homepage = "https://nezutero.dev"
